import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE
Obsidian DeepSeek Plugin - Claude Code
*/
`;

esbuild.build({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    platform: "node",
    external: ["obsidian"],
    format: "cjs",
    target: "es2020",
    minify: false,
    sourcemap: false,
    outfile: "main.js",
    logLevel: "info",
}).catch(() => process.exit(1));
